### ISSUE TITLE
Enhancement - Please support Aether Additions and Aether Continuation.

### ISSUE THREAD

**Issue by MagmaSlime123** [AerodGit/Jappafied-Aether#1]
Not much to say.

Would be nice if these 2 small 1.12 addons were jappa-fied until Aether for 1.18 is out.
Thanks, cool resourcepack.

https://www.curseforge.com/minecraft/mc-mods/aether-addon
https://www.curseforge.com/minecraft/mc-mods/aether-additions

**Comment by MagmaSlime123** [comment]
Forgot to mention https://www.curseforge.com/minecraft/mc-mods/extra-moas and https://www.curseforge.com/minecraft/mc-mods/spartan-compatibility also exists as well. Spartan Compat. adds Aether Spartan weapons.

**Comment by Mr-Aerod** [comment]
I might jappafy the Extra Moas addon, but I don't think I'll do the Spartan mod, just because it's a compatibility mod and there are thousands of mods of this kind and it wouldn't be worth jappafying every single one.

**Comment by MagmaSlime123** [comment]
I've only seen the Spartan Compat. addon do Aether. I'm not aware of any other Aether addons besides these.
