### ISSUE TITLE
Skyroot leaves have pink in the gaps when using fast graphics 

### ISSUE THREAD

**Issue by kodadacod** [AerodGit/Jappafied-Aether#3]
When using Fast graphics the gaps between the leaves of Skyroot Leaves blocks are pink instead of being black.
![2022-04-04_14 19 46](https://user-images.githubusercontent.com/75467920/161645507-7fc054e6-25c2-4ec4-9563-a77bcb4650e3.png)
.

**Comment by Mr-Aerod** [comment]
I have no idea what might be causing this or how to fix it. Dunno if this bug is even or our side, but I'll surely take a look into it.

**Comment by Mr-Aerod** [comment]
1.12 Aether leaves are fine, but something's wrong with the 1.18 ones...
![2022-04-06_17 42 00](https://user-images.githubusercontent.com/79194869/162014141-22cf50cd-6af8-4b76-82f6-d96e3324ebbd.png)

**Comment by Mr-Aerod** [comment]
These are the programmer art leaves. Weird... ![2022-04-06_17 44 15](https://user-images.githubusercontent.com/79194869/162014651-928568b6-6652-44cd-964d-1c984b0c6bd4.png)

**Comment by Mr-Aerod** [comment]
Fixed this by setting the colour mode to Indexed for all textures.
