### ISSUE TITLE
(Suggestion) Make the 1.19 textures be the default ones, and rename the addons to ‘Jappafied Aether [version] Textures’

### ISSUE THREAD

**Issue by Zepalesque** [AerodGit/Jappafied-Aether#9]
The 1.19 textures addon pack would make more sense to be part of the default resource pack, with there being an Aether Programmer Retextures addon or something like that, since the Aether has it’s programmer art textures as an extra resource pack too. It would probably also be a good idea to put in the pack.mcmeta description of the other two addons that they work best when using them with the programmer retextures addon (or whatever it would end up being called).

Also, the addon packs would probably be a little bit less confusing if they were called ‘Jappafied Aether [version] textures’ instead of ‘Aether [version] textures’, so that no one will get them mixed up with the Aether’s built-in resource packs.

**Comment by Mr-Aerod** [comment]
We'll take the first thing into consideration.

The addon paks are called like this because the full name you suggested wouldn't fit in the Minecraft's Resource pack selection, it would look like this in the game: "Jappafied Aether 1.19 te...".

**Comment by Mr-Aerod** [comment]
Nvm, renamed the Addon packs to a new, "Jappafied Aether <version>" format with a clear description.

**Comment by Mr-Aerod** [comment]
I'll do this in the near future.
